CREATE OR REPLACE FORCE VIEW "LOCAL".vw_contrato (numvivi,nominq,fecini,fecfin,renov,new_fecini,new_fecfin) AS
select
    VV.NUMVIVI, IQ.NOMINQ,
    AL.FECINI, AL.FECFIN, 
    CASE
        WHEN to_number(AL2.CODRENV) > 0 THEN 'CONTRATO RENOVADO'
        ELSE 'Fin'
    END RENOV, AL2.FECINI NEW_FECINI, AL2.FECFIN NEW_FECFIN
from ALQUILER AL
    inner JOIN ALQUILER AL2
        ON AL.CODALQU = AL2.CODRENV
    INNER JOIN VIVIENDA VV
        ON AL.CODVIVI = VV.CODVIVI
    INNER JOIN INQUILINO IQ
        ON IQ.CODINQ = AL.CODINQ
ORDER BY VV.NUMVIVI;